### ISSUE TITLE
Error for google search

### ISSUE THREAD

**Issue by Maninder-Singh2217** [advaith1/advaithbot#14]
<img width="528" alt="Capture" src="https://user-images.githubusercontent.com/43217891/68409175-a572fa80-01ac-11ea-80a4-e75b3ca50a76.PNG">
<img width="441" alt="Capture2" src="https://user-images.githubusercontent.com/43217891/68409228-b7549d80-01ac-11ea-901a-c8436066559d.PNG">

**Comment by advaith1** [comment]
It works fine for me, are you still getting that error?
![CE56F04F-39BC-4D92-BCB0-785A34DD8829](https://user-images.githubusercontent.com/11778454/68424237-6915af00-0158-11ea-9a2b-71814c45e629.jpeg)

**Comment by Maninder-Singh2217** [comment]
It worked for me too now, thanks for the response.
I had no knowledge about things mentioned in error details so considered posting here.
