### ISSUE TITLE
[BUG] selecting app info causes DiscordAPIError

### ISSUE THREAD

**Issue by Flyingbacen** [advaith1/advaithbot#19]
![image](https://github.com/user-attachments/assets/1b15c862-989b-43f9-bd42-23d72fc6adac)
1. press that button
![image](https://github.com/user-attachments/assets/b5a2ee1d-4e45-41a5-8941-07e5dbadff27)
2. get this error

**Comment by Flyingbacen** [comment]
if there's no way to disable that feature for non applications, add a custom text saying you can't do this or something similar instead of giving an Error

**Comment by advaith1** [comment]
The app info context menu command now checks if the user is a bot and returns a proper response if not.
