### ISSUE TITLE
Bug with !!say

### ISSUE THREAD

**Issue by RedDaedalus** [advaith1/advaithbot#7]
Typing `!!say !!say !!say !!say !!say !!say !!say !!say !!say !!say !!say !!say !!say !!say !!say !!say !!say !!say !!say !!say !!say a` will cause the bot to run the say command in a loop and eventually spit out "a"`. If possible you should make commands ignore all bots. (Discovered by @tuW#5374)

**Comment by advaith1** [comment]
This was fixed yesterday. Thanks for the report!
